### ISSUE TITLE
求助：使用过程中报错：KeyError: 'data'

### ISSUE THREAD

**Issue by smlover319** [LSQYES/BilibiliCommentsCrawler#6]
在pycharm社区版中完整报错代码如下：
视频名字: Top Gear 第33季, video_bv: BV1A54y1M7Tm
Traceback (most recent call last):
  File "M:\BilibiliCommentsCrawler-main\bili_comment.py", line 118, in <module>
    comments = fetch_comments(video_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\BilibiliCommentsCrawler-main\bili_comment.py", line 67, in fetch_comments
    if data and 'replies' in data['data']:
                             ~~~~^^^^^^^^
KeyError: 'data'

我应该咋办，急！

**Comment by wr0x00** [comment]
你看一下返回的json，应该是被ban了

**Comment by lmlqt** [comment]
> 你看一下返回的json，应该是被ban了
不对，返回正常，但是不能正确解析，我增加了      # 调试信息print(data)，发现输出了全部评论数据，可能是Bilibili的API返回的数据结构可能发生了变化，导致data['data']['replies']不再存在。
![Uploading image.png…]()
